services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: angular_dev_local
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules