server {
    listen 80;
    server_name _;

    # Redirigir todo el tráfico HTTP a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name outfitgo.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/outfitgo.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/outfitgo.duckdns.org/privkey.pem;

    # Opciones de seguridad SSL recomendadas
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    # Sirve el Frontend Angular
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirige el tráfico API al EC2 del Backend (usando su IP Privada)
    location /api {
        proxy_pass http://172.31.39.131;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin {
        proxy_pass http://172.31.39.131;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /storage {
        proxy_pass http://172.31.39.131;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
