name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npx ng build --configuration production --base-href /OutfitGo-frontend/

      - name: Copy index.html to 404.html for client-side routing
        run: cp dist/outfit-go-angular19/browser/index.html dist/outfit-go-angular19/browser/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/outfit-go-angular19/browser
          branch: gh-pages
